@table = login
@id = 11

@body = {"email" : "maka.albarn@deathcity.jp" , "password" : "PMLJnqkd67", "is_deleted" : 0}
# @body = {"title" : "écologie", "img_src" : "https://picsum.photos/id/237/200/300"}
GET http://blog.api/{{table}}
###
GET http://blog.api/{{table}}/{{id}}
### requête ThemeDetail
GET http://blog.api/themeDetail/{{id}}
### requête envoi de mail à mon adresse gmail
GET http://blog.api/test

###
POST http://blog.api/{{table}}
Content-Type: application/json

{{body}}

###
PUT http://blog.api/{{table}}/{{id}}
Content-Type: application/json

{{body}} 
###
PATCH http://blog.api/{{table}}/{{id}}
###
DELETE http://blog.api/{{table}}/{{id}}
